name: Compile

on: 
  push:
    branches:
      - main

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.25.1
      - name: Run compile
        run: deno compile --importmap import_map.json --target x86_64-pc-windows-msvc --output output/sample.exe src/**.ts
      - name: Upload compiled files
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: output/
          if-no-files-found: error
