name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.25.1
      - name: Run fmt
        run: |
          deno fmt src --check
      - name: Run lint
        run: |
          deno lint
      - name: Run tests
        run: |
          deno test
